[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "*"
ratatui = "*"
crossterm = "*"
clap = "*"
tokio = "*"
anyhow = "*"
futures = "*"
log = "*"
lib = { path = "../lib" }
serde_json = "*"

