[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "*", features = ["full"] }
env_logger = "*"
serde_json = "*"
surf = "*"
anyhow = "*"
log = "*"
lib = { path = "../lib" }
